import type { Pantry } from 'src/types/pantry';

const startDate = new Date('2023-01-01');
const endDate = new Date('2023-06-20');

const randomTimestamp = startDate.getTime() + Math.random() * (endDate.getTime() - startDate.getTime());


export const myPantry: Pantry[] = [
  {
    id: '5e887ac47eed253091be10cb',
    currency: '$',
    note: 'item notes',
    location1: true,
    location2: false,
    location3: false,
    location4: false,
    location5: true,
    name: 'pasta',
    updatedAt: new Date(randomTimestamp),
    price: 3.00,
    favorite: false,
    quantity: 4,
  },
  {
    id: '5e887b209c28ac3dd97f6db5',
    currency: '$',
    note: 'item notes',
    location1: false,
    location2: false,
    location3: true,
    location4: true,
    location5: false,
    name: 'Chicken',
    updatedAt: new Date(randomTimestamp),
    price: 0.00,
    favorite: false,
    quantity: 3,
  },
  {
    id: '5e887b7602bdbc4dbb234b27',
    currency: '$',
    note: 'item notes',
    location1: false,
    location2: true,
    location3: false,
    location4: false,
    location5: false,
    name: 'steak',
    updatedAt: new Date(randomTimestamp),
    price: 5.00,
    favorite: false,
    quantity: 6,
  },
  {
    id: '5e86809283e28b96d2d38537',
    currency: '$',
    note: 'item notes',
    location1: true,
    location2: false,
    location3: false,
    location4: false,
    location5: true,
    name: 'Strawberry',
    updatedAt: new Date(randomTimestamp),
    price: 5.00,
    favorite: false,
    quantity: 1,
  },
  {
    id: '5e86805e2bafd54f66cc95c3',
    currency: '$',
    note: 'item notes',
    location1: true,
    location2: false,
    location3: false,
    location4: true,
    location5: false,
    name: 'cheese',
    updatedAt: new Date(randomTimestamp),
    price: 0.00,
    favorite: false,
    quantity: 0,
  },
  {
    id: '5e887a1fbefd7938eea9c981',
    currency: '$',
    note: 'item notes',
    location1: false,
    location2: true,
    location3: false,
    location4: true,
    location5: false,
    name: 'broccoli',
    updatedAt: new Date(randomTimestamp),
    price: 0.00,
    favorite: false,
    quantity: 3,
  },
  {
    id: '5e887d0b3d090c1b8f162003',
    currency: '$',
    note: 'item notes',
    location1: true,
    location2: false,
    location3: false,
    location4: false,
    location5: false,
    name: 'chocolate',
    updatedAt: new Date(randomTimestamp),
    price: 10.00,
    favorite: false,
    quantity: 1,
  },
  {
    id: '5e88792be2d4cfb4bf0971d9',
    currency: '$',
    note: 'item notes',
    location1: true,
    location2: false,
    location3: false,
    location4: false,
    location5: true,
    name: 'potato chips',
    updatedAt: new Date(randomTimestamp),
    price: 10.00,
    favorite: false,
    quantity: 2,
  },
  {
    id: '5e8877da9a65442b11551975',
    currency: '$',
    note: 'item notes',
    location1: false,
    location2: false,
    location3: true,
    location4: true,
    location5: false,
    name: 'ice cream',
    updatedAt: new Date(randomTimestamp),
    price: 0.00,
    favorite: false,
    quantity: 0,
  },
  {
    id: '5e8680e60cba5019c5ca6fda',
    currency: '$',
    note: 'item notes',
    location1: false,
    location2: false,
    location3: true,
    location4: false,
    location5: true,
    name: 'chicken nuggets',
    updatedAt: new Date(randomTimestamp),
    price: 2.00,
    favorite: false,
    quantity: 4,
  }
];

export const pantry: Pantry = {
  id: '5e8680e60cba5019c5ca6fda',
  currency: '$',
  note: 'item notes',
  location1: false,
  location2: false,
  location3: true,
  location4: false,
  location5: true,
  name: 'chicken nuggets',
  updatedAt: new Date(randomTimestamp),
  price: 2.00,
  favorite: false,
  quantity: 3,
};